version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=$MYSQL_DB_NAME
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
        - "33060:3306"


  aprobousapi:
    image: test
    container_name: aprobousapi
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
      - APP_PORT=3333
      - MYSQL_HOST=mysql
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB_NAME=$MYSQL_DB_NAME
      - MYSQL_PORT=$MYSQL_PORT
      - PORT=3333
      - HOST=0.0.0.0
      - APP_KEY=Dj9PVALBH5PBb7gXlXB1WCoXzfk1y0Pl
      - DB_CONNECTION=mysql
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: node ace serve -w

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
